# Generated by Django 6.0.4 on 2026-05-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_booking_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_distance',
            field=models.FloatField(blank=True, help_text='Distance in km', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per km', max_digits=10, null=True),
        ),
    ]
